[package]
name = "secret-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-nats.workspace = true
async-trait.workspace = true
authz-domain = { path = "../authz-domain" }
authz-postgres = { path = "../authz-postgres" }
forge-domain = { path = "../forge-domain" }
identity-domain = { path = "../identity-domain" }
release-domain = { path = "../release-domain" }
runtime-types = { path = "../runtime-types" }
secret-domain = { path = "../secret-domain" }
secret-store = { path = "../secret-store" }
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
serial_test = "3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
