[package]
name = "secret-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata.hephaestus]
layer = "application"
context = "secret"

[dependencies]
secret-application = { path = "../secret-application" }

[dev-dependencies]
serial_test = "3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
