#!/bin/sh
set -eu

output=''
while [ "$#" -gt 0 ]; do
    case "$1" in
        --output)
            output=$2
            shift 2
            ;;
        *) shift ;;
    esac
done

[ -n "$output" ]
printf '%s\n' '{"SchemaVersion":2,"ArtifactName":"repository-builder-e2e","ArtifactType":"oci","Results":[]}' >"$output"
