use super::*;

pub type RpcTokenFactory = Arc<dyn Fn(&str) -> String + Send + Sync>;

/// Owned inputs that let the cooking proof run outside the top-level test.
#[allow(clippy::struct_excessive_bools)]
pub struct CookingFlowInput {
    pub pool: sqlx::PgPool,
    pub running: hephaestus_app::RunningHephaestus,
    pub app_config: AppConfig,
    pub database_url: String,
    pub nats_url: String,
    pub root: PathBuf,
    pub fixture_repository: PgForgeRepository,
    pub browser_oidc_issuer: String,
    pub user_id: UserId,
    pub organization_id: OrganizationId,
    pub owner_browser_session: BrowserSessionSid,
    pub outsider_id: UserId,
    pub outsider_browser_session: BrowserSessionSid,
    pub project: forge_domain::Project,
    pub observer: Option<Arc<support::vm_observer::VmSpecObserver>>,
    pub workload_phase_timing: bool,
    pub release_build_proof: bool,
    pub libkrun_e2e: bool,
    pub session_chat_e2e: bool,
    pub installed_ui_fixture: bool,
    pub browser_e2e: bool,
    pub cooking_service_build_proof: bool,
    pub caddy_tls: bool,
    pub cooking_wait_timeout: Duration,
}

/// Cooking state produced by the setup stages and consumed by later probes.
pub struct CookingPreparation {
    pub pool: sqlx::PgPool,
    pub running: Option<hephaestus_app::RunningHephaestus>,
    pub app_config: Option<AppConfig>,
    pub database_url: String,
    pub nats_url: String,
    pub root: PathBuf,
    pub source_root: PathBuf,
    pub fixture_repository: PgForgeRepository,
    pub browser_oidc_issuer: String,
    pub user_id: UserId,
    pub organization_id: OrganizationId,
    pub owner_browser_session: BrowserSessionSid,
    pub outsider_id: UserId,
    pub outsider_browser_session: BrowserSessionSid,
    pub project: forge_domain::Project,
    pub observer: Option<Arc<support::vm_observer::VmSpecObserver>>,
    pub workload_phase_timing: bool,
    pub browser_e2e: bool,
    pub cooking_wait_timeout: Duration,
    pub identity: AuthenticatedIdentity,
    pub token: String,
    pub rpc_token: RpcTokenFactory,
    pub retry_fixture: Option<ForgeRetryFixture>,
    pub builds: cooking_builds::PublishedCookingBuilds,
    pub blog_repository: cooking_builds::PreparedCookingBlog,
    pub instance: cooking_builds::PreparedCookingInstance,
    pub actual_instance: SeededInstance,
    pub actual_brokered: BrokeredFixture,
    pub cooking_update_rule_ids: Option<(
        cooking_updates::BrokeredRuleIds,
        cooking_updates::BrokeredRuleIds,
        cooking_updates::BrokeredRuleIds,
        cooking_updates::BrokeredRuleIds,
    )>,
    pub cooking_inbound_placeholder: String,
    pub actual_fixture: GatewayGoldenFixture,
    pub adversarial_configured: cooking_builds::ConfiguredCookingGateway,
    pub adversarial_foreign_mailbox: uuid::Uuid,
    pub canonical_revision_id: uuid::Uuid,
    pub adversarial_instance: cooking_builds::PreparedCookingInstance,
    pub adversarial_rule_id: uuid::Uuid,
    pub update_builds: Option<cooking_builds::PublishedCookingUpdateBuilds>,
}

#[allow(clippy::struct_excessive_bools)]
pub struct StandardFlowInput {
    pub pool: sqlx::PgPool,
    pub running: hephaestus_app::RunningHephaestus,
    pub app_config: AppConfig,
    pub root: PathBuf,
    pub nats_url: String,
    pub repository: forge_domain::Repository,
    pub project: forge_domain::Project,
    pub seeded_instance: SeededInstance,
    pub token: String,
    pub libkrun_e2e: bool,
    pub user_id: UserId,
    pub owner_browser_session: BrowserSessionSid,
    pub outsider_id: UserId,
    pub outsider_browser_session: BrowserSessionSid,
    pub gateway_caddy_e2e: bool,
    pub gateway_service_e2e: bool,
    pub gateway_service_log_guest_e2e: bool,
    pub gateway_service_log_rpc_e2e: bool,
    pub gateway_edge: Option<(GatewayEdgeConfig, GatewayGoldenFixture)>,
    pub gateway_service_fixture: Option<GatewayServiceGoldenFixture>,
    pub brokered_fixture: Option<BrokeredFixture>,
}
