//! Provider-neutral persistence port for release-owned browser UI sessions.
//!
//! This port deliberately stops at the release boundary. It does not define
//! RPC messages, HTTP cookies, Caddy host lookup, or SQL. Implementations must
//! persist only the domain-separated digests of the supplied secrets.

use async_trait::async_trait;
use gateway_domain::{HttpMethod, RoutePath};
use identity_domain::{BrowserSessionId, OrganizationId, RequestId, UserId};
use release_domain::{
    UiInstallationGenerationId, UiInstallationId,
    ui_browser::{
        UiBrowserHandoffId, UiBrowserHandoffSecret, UiBrowserRoute, UiBrowserSessionId,
        UiBrowserSessionSecret,
    },
};
use std::fmt;
use thiserror::Error;
use time::OffsetDateTime;

/// A trusted actor asks to bind a new one-time handoff to one exact UI
/// generation and initial route.
///
/// The actor and parent session are both required. The parent session ID is
/// an internal identity, not transport authority; implementations must verify
/// that it belongs to `actor_id`, is active, and has not expired or been
/// revoked. The organization is intentionally absent and must be derived from
/// the installation owner in the transaction.
pub struct CreateUiBrowserHandoff {
    /// Correlation identifier for the trusted request and any later audit
    /// record. It does not become part of the bearer credential.
    pub request_id: RequestId,
    /// Current authenticated user requesting the handoff.
    pub actor_id: UserId,
    /// Internal durable human browser-session identity.
    pub parent_session_id: BrowserSessionId,
    /// Stable installation selected by the trusted host.
    pub installation_id: UiInstallationId,
    /// Immutable generation selected by the trusted host.
    pub generation_id: UiInstallationGenerationId,
    /// Initial route selected from the published UI declaration.
    pub route: UiBrowserRoute,
    /// Raw handoff bearer supplied only at the sensitive Phoenix boundary.
    pub secret: UiBrowserHandoffSecret,
}

/// Safe metadata returned after a handoff is durably created.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreatedUiBrowserHandoff {
    /// Internal handoff row identity.
    pub handoff_id: UiBrowserHandoffId,
    /// Exact actor bound to the parent session.
    pub actor_id: UserId,
    /// Internal parent-session identity.
    pub parent_session_id: BrowserSessionId,
    /// Organization derived from the installation owner.
    pub organization_id: OrganizationId,
    /// Stable installation identity.
    pub installation_id: UiInstallationId,
    /// Immutable generation bound to the handoff.
    pub generation_id: UiInstallationGenerationId,
    /// Validated initial route.
    pub route: UiBrowserRoute,
    /// Fixed handoff expiry, exactly at most sixty seconds after issue.
    pub expires_at: OffsetDateTime,
}

/// Exchanges one unconsumed handoff for one generation-bound child session.
///
/// `expected_generation_id` comes from the platform-owned UI host resolution;
/// it is checked against the handoff before the transaction creates the child.
/// The child secret is generated by Phoenix and is returned only through the
/// explicit host-only cookie boundary. It must never appear in a result,
/// event, log, or database row in plaintext.
pub struct ExchangeUiBrowserHandoff {
    /// Correlation identifier for the trusted exchange and any later audit
    /// record. It does not become part of the child credential.
    pub request_id: RequestId,
    /// Raw one-time handoff bearer received by the bootstrap POST.
    pub handoff_secret: UiBrowserHandoffSecret,
    /// Generation selected by the platform-owned UI host.
    pub expected_generation_id: UiInstallationGenerationId,
    /// Raw child bearer to place in the separate host-only cookie.
    pub child_secret: UiBrowserSessionSecret,
}

/// Safe child-session metadata returned after an atomic handoff exchange.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreatedUiBrowserSession {
    /// Safe generation-bound session context.
    pub context: UiBrowserSessionContext,
}

/// The safe authorization context for one validated child session.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UiBrowserSessionContext {
    /// Internal child-session row identity.
    pub session_id: UiBrowserSessionId,
    /// Internal durable parent-session identity.
    pub parent_session_id: BrowserSessionId,
    /// Current account resolved from the parent session.
    pub actor_id: UserId,
    /// Organization derived from the installation owner.
    pub organization_id: OrganizationId,
    /// Stable installation identity.
    pub installation_id: UiInstallationId,
    /// Immutable generation identity.
    pub generation_id: UiInstallationGenerationId,
    /// Intended initial route bound to the child session.
    pub route: UiBrowserRoute,
    /// Fixed child expiry, capped by the parent expiry.
    pub expires_at: OffsetDateTime,
}

/// A request route whose declaration kind and method must be checked against
/// the immutable release publication before a child request is admitted.
///
/// Parsing one path is insufficient. The adapter must resolve the exact
/// generation's descriptor and then require a matching static file, managed
/// service binding, or API binding. API routes use the canonical absolute
/// gateway path and exact HTTP method; UI documents/assets use the declaration's
/// relative namespace. Unknown namespaces and undeclared routes fail closed.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum UiBrowserRequestRoute {
    /// A declared static document or asset relative to the UI namespace.
    /// The Rust UI handler resolves this platform-relative path beneath the
    /// declaration's `route_base` before serving the verified artifact.
    Static {
        /// Platform-relative route within the declaration's `route_base`.
        route: UiBrowserRoute,
    },
    /// A declared managed-service entrypoint or descendant route.
    /// The Rust UI handler resolves this platform-relative path beneath the
    /// declaration's `route_base` before forwarding to the managed gateway.
    Managed {
        /// Platform-relative route within the declaration's `route_base`.
        route: UiBrowserRoute,
    },
    /// A declared authenticated gateway API route and exact method.
    Api {
        /// Canonical absolute gateway route.
        route: RoutePath,
        /// Exact HTTP method required by the declaration.
        method: HttpMethod,
    },
}

impl UiBrowserRequestRoute {
    /// Returns the route text for diagnostics without exposing credentials.
    #[must_use]
    pub fn route_text(&self) -> &str {
        match self {
            Self::Static { route } | Self::Managed { route } => route.as_str(),
            Self::Api { route, .. } => route.as_str(),
        }
    }
}

/// Validates a child cookie against one exact generation and request route.
pub struct AuthenticateUiBrowserSession {
    /// Raw child bearer received from the host-only cookie.
    pub session_secret: UiBrowserSessionSecret,
    /// Generation selected by the platform-owned UI host.
    pub expected_generation_id: UiInstallationGenerationId,
    /// Exact declaration kind and route being requested.
    pub request_route: UiBrowserRequestRoute,
}

/// Failure categories for issuing or exchanging a handoff.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum UiBrowserHandoffError {
    /// The actor, parent session, owner, source release, or bound agent is not
    /// currently authorized for this exact generation.
    #[error("UI browser handoff is not authorized")]
    PermissionDenied,
    /// The route is not declared by the exact published UI/gateway binding.
    #[error("UI browser route is not declared")]
    InvalidRoute,
    /// The persistence provider failed or returned an invalid stored state.
    #[error("UI browser handoff persistence is unavailable")]
    Unavailable,
    /// The handoff was already consumed, expired, or bound to another host.
    #[error("UI browser handoff is invalid or expired")]
    InvalidOrExpired,
}

/// Failure categories for validating a child session.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum UiBrowserSessionError {
    /// The child secret, parent account, generation, organization, route, or
    /// current permission state is not valid for this request.
    #[error("UI browser session is unauthenticated")]
    Unauthenticated,
    /// The persistence provider failed or returned an invalid stored state.
    #[error("UI browser session persistence is unavailable")]
    Unavailable,
}

/// Provider-neutral persistence boundary for generation-bound UI browser
/// access.
#[async_trait]
pub trait UiBrowserSessionStore: Send + Sync {
    /// Persists a one-time handoff with a fixed sixty-second lifetime.
    ///
    /// The implementation must use one transaction that locks and rechecks
    /// the parent account/session, exact installation generation, current
    /// lifecycle, organization, route declaration, target permissions, source
    /// release permission, and every bound release-agent permission. It must
    /// derive organization from the installation and store only the handoff
    /// digest. No parent SID is accepted or persisted here.
    async fn create_ui_browser_handoff(
        &self,
        command: CreateUiBrowserHandoff,
    ) -> Result<CreatedUiBrowserHandoff, UiBrowserHandoffError>;

    /// Atomically consumes one handoff and creates one child session.
    ///
    /// The implementation must lock the handoff and parent session, recheck
    /// parent/account/generation/lifecycle/organization/permission state, and
    /// compute the child expiry as the lesser of twelve hours and the current
    /// parent expiry. A concurrent or repeated exchange must create at most
    /// one child; consumed handoffs are never reusable. Only the child digest
    /// may be persisted.
    async fn exchange_ui_browser_handoff(
        &self,
        command: ExchangeUiBrowserHandoff,
    ) -> Result<CreatedUiBrowserSession, UiBrowserHandoffError>;

    /// Validates one child cookie for one exact host generation and route.
    ///
    /// Every request must recheck the parent session's current revocation and
    /// expiry, the current account status, installation lifecycle/current
    /// generation, organization ownership, target/source/agent permissions,
    /// and the exact static/managed/API declaration. The selected navigation
    /// organization is never an authority input. Implementations must return
    /// only safe context and never expose a digest, SID, credential, or source
    /// storage locator.
    async fn authenticate_ui_browser_session(
        &self,
        command: AuthenticateUiBrowserSession,
    ) -> Result<UiBrowserSessionContext, UiBrowserSessionError>;
}

impl fmt::Display for UiBrowserRequestRoute {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.route_text())
    }
}
