use super::{
    MAX_PAT_LABEL_BYTES, PAT_FORMAT_VERSION, PAT_PREFIX, PAT_SECRET_BYTES, PAT_VERIFIER_DOMAIN,
    REDACTED, errors::PersonalAccessTokenError,
};
use serde::{Deserialize, Serialize, Serializer};
use sha2::{Digest, Sha256};
use std::{fmt, str::FromStr};
use uuid::Uuid;

/// Stable, non-secret identifier encoded into a PAT.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct PersonalAccessTokenId(Uuid);

impl PersonalAccessTokenId {
    /// Creates a cryptographically random version 4 identifier.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Creates an identifier from a UUID.
    #[must_use]
    pub const fn from_uuid(value: Uuid) -> Self {
        Self(value)
    }

    /// Returns the underlying UUID.
    #[must_use]
    pub const fn as_uuid(self) -> Uuid {
        self.0
    }
}

impl Default for PersonalAccessTokenId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for PersonalAccessTokenId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.hyphenated().fmt(formatter)
    }
}

impl FromStr for PersonalAccessTokenId {
    type Err = PersonalAccessTokenError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        let uuid = Uuid::parse_str(value).map_err(|_| PersonalAccessTokenError::InvalidToken)?;
        if uuid.hyphenated().to_string() != value {
            return Err(PersonalAccessTokenError::InvalidToken);
        }
        Ok(Self(uuid))
    }
}

/// User-visible, non-secret label used to distinguish PATs safely.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct PersonalAccessTokenLabel(String);

impl PersonalAccessTokenLabel {
    /// Validates a bounded label without including rejected input in errors.
    ///
    /// # Errors
    ///
    /// Returns [`PersonalAccessTokenError::InvalidLabel`] when the label is
    /// empty, has surrounding whitespace, contains control characters, or is
    /// too large.
    pub fn parse(value: impl Into<String>) -> Result<Self, PersonalAccessTokenError> {
        let value = value.into();
        if value.is_empty()
            || value.len() > MAX_PAT_LABEL_BYTES
            || value.trim() != value
            || value.chars().any(char::is_control)
        {
            return Err(PersonalAccessTokenError::InvalidLabel);
        }
        Ok(Self(value))
    }

    /// Returns the validated label.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for PersonalAccessTokenLabel {
    type Error = PersonalAccessTokenError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::parse(value)
    }
}

impl From<PersonalAccessTokenLabel> for String {
    fn from(value: PersonalAccessTokenLabel) -> Self {
        value.0
    }
}

/// A versioned opaque PAT containing a lookup identifier and bearer secret.
///
/// The secret must be generated by a cryptographically secure random source
/// at the application boundary. This type intentionally does not implement
/// `Clone` or `Deserialize`.
pub struct PersonalAccessToken {
    id: PersonalAccessTokenId,
    secret: [u8; PAT_SECRET_BYTES],
}

impl PersonalAccessToken {
    /// Constructs a version 1 token from CSPRNG-produced secret bytes.
    #[must_use]
    pub const fn from_secret(id: PersonalAccessTokenId, secret: [u8; PAT_SECRET_BYTES]) -> Self {
        Self { id, secret }
    }

    /// Parses the exact canonical version 1 PAT envelope.
    ///
    /// # Errors
    ///
    /// Returns [`PersonalAccessTokenError::InvalidToken`] for every malformed
    /// input so errors cannot echo or classify bearer material.
    pub fn parse(value: &str) -> Result<Self, PersonalAccessTokenError> {
        let mut fields = value.split('.');
        let prefix = fields.next();
        let id = fields.next();
        let encoded_secret = fields.next();
        if prefix != Some(PAT_PREFIX) || fields.next().is_some() {
            return Err(PersonalAccessTokenError::InvalidToken);
        }
        let id = id
            .ok_or(PersonalAccessTokenError::InvalidToken)?
            .parse::<PersonalAccessTokenId>()?;
        let secret = decode_secret(encoded_secret.ok_or(PersonalAccessTokenError::InvalidToken)?)?;
        Ok(Self { id, secret })
    }

    /// Returns the non-secret identifier used for verifier lookup.
    #[must_use]
    pub const fn id(&self) -> PersonalAccessTokenId {
        self.id
    }

    /// Encodes plaintext bearer material for its one authorized boundary.
    ///
    /// Callers must not log, persist, or place the returned value in a Git
    /// remote URL or repository configuration.
    #[must_use]
    pub fn expose(&self) -> String {
        let mut encoded = String::with_capacity(PAT_PREFIX.len() + 1 + 36 + 1 + 64);
        encoded.push_str(PAT_PREFIX);
        encoded.push('.');
        encoded.push_str(&self.id.to_string());
        encoded.push('.');
        encode_hex_into(&self.secret, &mut encoded);
        encoded
    }

    /// Derives the one-way representation suitable for durable storage.
    #[must_use]
    pub fn verifier(&self) -> PersonalAccessTokenVerifier {
        let mut digest = Sha256::new();
        digest.update(PAT_VERIFIER_DOMAIN);
        digest.update(self.id.as_uuid().as_bytes());
        digest.update(self.secret);
        PersonalAccessTokenVerifier {
            version: PAT_FORMAT_VERSION,
            digest: digest.finalize().into(),
        }
    }
}

impl Drop for PersonalAccessToken {
    fn drop(&mut self) {
        for byte in &mut self.secret {
            *std::hint::black_box(byte) = 0;
        }
    }
}

impl fmt::Debug for PersonalAccessToken {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("PersonalAccessToken([REDACTED])")
    }
}

impl fmt::Display for PersonalAccessToken {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(REDACTED)
    }
}

impl Serialize for PersonalAccessToken {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(REDACTED)
    }
}

/// Domain-separated one-way PAT verifier safe for durable storage.
#[derive(Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct PersonalAccessTokenVerifier {
    version: u16,
    digest: [u8; 32],
}

impl PersonalAccessTokenVerifier {
    /// Restores a verifier from its durable version and digest.
    ///
    /// Persisted verifier bytes are one-way material and never contain the
    /// plaintext token secret.
    #[must_use]
    pub const fn from_digest(version: u16, digest: [u8; 32]) -> Self {
        Self { version, digest }
    }

    /// Returns the verifier construction version.
    #[must_use]
    pub const fn version(self) -> u16 {
        self.version
    }

    /// Returns the one-way digest for durable storage.
    #[must_use]
    pub const fn digest(self) -> [u8; 32] {
        self.digest
    }

    /// Compares a plaintext token to this verifier without an early exit on
    /// digest bytes.
    #[must_use]
    pub fn verifies(self, token: &PersonalAccessToken) -> bool {
        if self.version != PAT_FORMAT_VERSION {
            return false;
        }
        constant_time_eq(&self.digest, &token.verifier().digest)
    }
}

impl fmt::Debug for PersonalAccessTokenVerifier {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("PersonalAccessTokenVerifier([REDACTED])")
    }
}

fn decode_secret(encoded: &str) -> Result<[u8; PAT_SECRET_BYTES], PersonalAccessTokenError> {
    if encoded.len() != PAT_SECRET_BYTES * 2 {
        return Err(PersonalAccessTokenError::InvalidToken);
    }
    let mut secret = [0_u8; PAT_SECRET_BYTES];
    for (index, pair) in encoded.as_bytes().chunks_exact(2).enumerate() {
        let high = decode_hex_nibble(pair[0]).ok_or(PersonalAccessTokenError::InvalidToken)?;
        let low = decode_hex_nibble(pair[1]).ok_or(PersonalAccessTokenError::InvalidToken)?;
        secret[index] = (high << 4) | low;
    }
    Ok(secret)
}

const fn decode_hex_nibble(value: u8) -> Option<u8> {
    match value {
        b'0'..=b'9' => Some(value - b'0'),
        b'a'..=b'f' => Some(value - b'a' + 10),
        _ => None,
    }
}

fn encode_hex_into(bytes: &[u8], output: &mut String) {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for byte in bytes {
        output.push(char::from(HEX[usize::from(byte >> 4)]));
        output.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
}

fn constant_time_eq(left: &[u8; 32], right: &[u8; 32]) -> bool {
    let difference = left
        .iter()
        .zip(right)
        .fold(0_u8, |difference, (left, right)| {
            difference | (left ^ right)
        });
    difference == 0
}
