//! Provider-neutral developer personal access token contracts.
//!
//! A [`PersonalAccessToken`] is plaintext bearer material. It can be exposed
//! only through an explicit method, is redacted from formatting and
//! serialization, and should live only long enough to cross the issuance or
//! authentication boundary. Durable state is represented by
//! [`PersonalAccessTokenRecord`], which contains only a domain-separated
//! one-way verifier and safe lifecycle metadata.

use forge_domain::RepositoryId;
use git_capability_domain::GitOperation;
use identity_domain::{RequestId, UserId};
use serde::{Deserialize, Serialize, Serializer};
use sha2::{Digest, Sha256};
use std::{collections::BTreeSet, fmt, str::FromStr};
use time::{Duration, OffsetDateTime};
use uuid::Uuid;

/// Version of the plaintext PAT envelope and verifier construction.
pub const PAT_FORMAT_VERSION: u16 = 1;
/// Maximum lifetime accepted for a newly issued developer PAT.
pub const MAX_PAT_LIFETIME: Duration = Duration::days(90);
/// Maximum number of exact repository restrictions on one PAT.
pub const MAX_REPOSITORY_RESTRICTIONS: usize = 128;
/// Maximum number of UTF-8 bytes in a user-visible PAT label.
pub const MAX_PAT_LABEL_BYTES: usize = 128;

const PAT_PREFIX: &str = "heph_pat_v1";
const PAT_SECRET_BYTES: usize = 32;
const PAT_VERIFIER_DOMAIN: &[u8] = b"hephaestus-developer-pat-verifier-v1\0";
const REDACTED: &str = "[REDACTED]";

/// Stable, non-secret identifier encoded into a PAT.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(transparent)]
pub struct PersonalAccessTokenId(Uuid);

impl PersonalAccessTokenId {
    /// Creates a cryptographically random version 4 identifier.
    #[must_use]
    pub fn new() -> Self {
        Self(Uuid::new_v4())
    }

    /// Creates an identifier from a UUID.
    #[must_use]
    pub const fn from_uuid(value: Uuid) -> Self {
        Self(value)
    }

    /// Returns the underlying UUID.
    #[must_use]
    pub const fn as_uuid(self) -> Uuid {
        self.0
    }
}

impl Default for PersonalAccessTokenId {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for PersonalAccessTokenId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.0.hyphenated().fmt(formatter)
    }
}

impl FromStr for PersonalAccessTokenId {
    type Err = PersonalAccessTokenError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        let uuid = Uuid::parse_str(value).map_err(|_| PersonalAccessTokenError::InvalidToken)?;
        if uuid.hyphenated().to_string() != value {
            return Err(PersonalAccessTokenError::InvalidToken);
        }
        Ok(Self(uuid))
    }
}

/// User-visible, non-secret label used to distinguish PATs safely.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct PersonalAccessTokenLabel(String);

impl PersonalAccessTokenLabel {
    /// Validates a bounded label without including rejected input in errors.
    ///
    /// # Errors
    ///
    /// Returns [`PersonalAccessTokenError::InvalidLabel`] when the label is
    /// empty, has surrounding whitespace, contains control characters, or is
    /// too large.
    pub fn parse(value: impl Into<String>) -> Result<Self, PersonalAccessTokenError> {
        let value = value.into();
        if value.is_empty()
            || value.len() > MAX_PAT_LABEL_BYTES
            || value.trim() != value
            || value.chars().any(char::is_control)
        {
            return Err(PersonalAccessTokenError::InvalidLabel);
        }
        Ok(Self(value))
    }

    /// Returns the validated label.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl TryFrom<String> for PersonalAccessTokenLabel {
    type Error = PersonalAccessTokenError;

    fn try_from(value: String) -> Result<Self, Self::Error> {
        Self::parse(value)
    }
}

impl From<PersonalAccessTokenLabel> for String {
    fn from(value: PersonalAccessTokenLabel) -> Self {
        value.0
    }
}

/// A versioned opaque PAT containing a lookup identifier and bearer secret.
///
/// The secret must be generated by a cryptographically secure random source
/// at the application boundary. This type intentionally does not implement
/// `Clone` or `Deserialize`.
pub struct PersonalAccessToken {
    id: PersonalAccessTokenId,
    secret: [u8; PAT_SECRET_BYTES],
}

impl PersonalAccessToken {
    /// Constructs a version 1 token from CSPRNG-produced secret bytes.
    #[must_use]
    pub const fn from_secret(id: PersonalAccessTokenId, secret: [u8; PAT_SECRET_BYTES]) -> Self {
        Self { id, secret }
    }

    /// Parses the exact canonical version 1 PAT envelope.
    ///
    /// # Errors
    ///
    /// Returns [`PersonalAccessTokenError::InvalidToken`] for every malformed
    /// input so errors cannot echo or classify bearer material.
    pub fn parse(value: &str) -> Result<Self, PersonalAccessTokenError> {
        let mut fields = value.split('.');
        let prefix = fields.next();
        let id = fields.next();
        let encoded_secret = fields.next();
        if prefix != Some(PAT_PREFIX) || fields.next().is_some() {
            return Err(PersonalAccessTokenError::InvalidToken);
        }
        let id = id
            .ok_or(PersonalAccessTokenError::InvalidToken)?
            .parse::<PersonalAccessTokenId>()?;
        let secret = decode_secret(encoded_secret.ok_or(PersonalAccessTokenError::InvalidToken)?)?;
        Ok(Self { id, secret })
    }

    /// Returns the non-secret identifier used for verifier lookup.
    #[must_use]
    pub const fn id(&self) -> PersonalAccessTokenId {
        self.id
    }

    /// Encodes plaintext bearer material for its one authorized boundary.
    ///
    /// Callers must not log, persist, or place the returned value in a Git
    /// remote URL or repository configuration.
    #[must_use]
    pub fn expose(&self) -> String {
        let mut encoded = String::with_capacity(PAT_PREFIX.len() + 1 + 36 + 1 + 64);
        encoded.push_str(PAT_PREFIX);
        encoded.push('.');
        encoded.push_str(&self.id.to_string());
        encoded.push('.');
        encode_hex_into(&self.secret, &mut encoded);
        encoded
    }

    /// Derives the one-way representation suitable for durable storage.
    #[must_use]
    pub fn verifier(&self) -> PersonalAccessTokenVerifier {
        let mut digest = Sha256::new();
        digest.update(PAT_VERIFIER_DOMAIN);
        digest.update(self.id.as_uuid().as_bytes());
        digest.update(self.secret);
        PersonalAccessTokenVerifier {
            version: PAT_FORMAT_VERSION,
            digest: digest.finalize().into(),
        }
    }
}

impl Drop for PersonalAccessToken {
    fn drop(&mut self) {
        for byte in &mut self.secret {
            *std::hint::black_box(byte) = 0;
        }
    }
}

impl fmt::Debug for PersonalAccessToken {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("PersonalAccessToken([REDACTED])")
    }
}

impl fmt::Display for PersonalAccessToken {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(REDACTED)
    }
}

impl Serialize for PersonalAccessToken {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(REDACTED)
    }
}

/// Domain-separated one-way PAT verifier safe for durable storage.
#[derive(Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct PersonalAccessTokenVerifier {
    version: u16,
    digest: [u8; 32],
}

impl PersonalAccessTokenVerifier {
    /// Restores a verifier from its durable version and digest.
    ///
    /// Persisted verifier bytes are one-way material and never contain the
    /// plaintext token secret.
    #[must_use]
    pub const fn from_digest(version: u16, digest: [u8; 32]) -> Self {
        Self { version, digest }
    }

    /// Returns the verifier construction version.
    #[must_use]
    pub const fn version(self) -> u16 {
        self.version
    }

    /// Returns the one-way digest for durable storage.
    #[must_use]
    pub const fn digest(self) -> [u8; 32] {
        self.digest
    }

    /// Compares a plaintext token to this verifier without an early exit on
    /// digest bytes.
    #[must_use]
    pub fn verifies(self, token: &PersonalAccessToken) -> bool {
        if self.version != PAT_FORMAT_VERSION {
            return false;
        }
        constant_time_eq(&self.digest, &token.verifier().digest)
    }
}

impl fmt::Debug for PersonalAccessTokenVerifier {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("PersonalAccessTokenVerifier([REDACTED])")
    }
}

/// Explicit Git operations and optional exact-repository narrowing for a PAT.
///
/// An absent repository restriction means the token can participate in live
/// authorization for any repository; it never bypasses the owner's current
/// repository authorization.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct PersonalAccessTokenScope {
    operations: BTreeSet<GitOperation>,
    repository_restrictions: Option<BTreeSet<RepositoryId>>,
}

impl PersonalAccessTokenScope {
    /// Normalizes a non-empty operation set and optional repository set.
    ///
    /// # Errors
    ///
    /// Returns an error for no operations, an explicitly empty repository
    /// restriction, or too many restricted repositories.
    pub fn new(
        operations: impl IntoIterator<Item = GitOperation>,
        repository_restrictions: Option<impl IntoIterator<Item = RepositoryId>>,
    ) -> Result<Self, PersonalAccessTokenError> {
        let operations = operations.into_iter().collect::<BTreeSet<_>>();
        if operations.is_empty() {
            return Err(PersonalAccessTokenError::EmptyScope);
        }
        let repository_restrictions = repository_restrictions
            .map(|repositories| repositories.into_iter().collect::<BTreeSet<_>>());
        if repository_restrictions
            .as_ref()
            .is_some_and(|repositories| {
                repositories.is_empty() || repositories.len() > MAX_REPOSITORY_RESTRICTIONS
            })
        {
            return Err(PersonalAccessTokenError::InvalidRepositoryRestrictions);
        }
        Ok(Self {
            operations,
            repository_restrictions,
        })
    }

    /// Returns the normalized operation set.
    #[must_use]
    pub const fn operations(&self) -> &BTreeSet<GitOperation> {
        &self.operations
    }

    /// Returns exact repository restrictions, or `None` for no token-level
    /// narrowing beyond mandatory live user authorization.
    #[must_use]
    pub const fn repository_restrictions(&self) -> Option<&BTreeSet<RepositoryId>> {
        self.repository_restrictions.as_ref()
    }

    /// Returns whether the requested operation and repository fit this token
    /// scope. The caller must separately check current user authorization.
    #[must_use]
    pub fn permits(&self, operation: GitOperation, repository_id: RepositoryId) -> bool {
        self.operations.contains(&operation)
            && self
                .repository_restrictions
                .as_ref()
                .is_none_or(|repositories| repositories.contains(&repository_id))
    }
}

/// Lifecycle classification at one trusted wall-clock instant.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PersonalAccessTokenStatus {
    /// The supplied instant predates creation metadata.
    NotYetValid,
    /// The PAT is active, subject to scope and live user authorization.
    Active,
    /// The PAT was explicitly revoked and cannot become active again.
    Revoked,
    /// The exclusive expiry has passed.
    Expired,
}

/// Safe API/listing snapshot that deliberately excludes the verifier.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct PersonalAccessTokenMetadata {
    /// Stable, non-secret token identifier.
    pub id: PersonalAccessTokenId,
    /// User who delegated authority through this PAT.
    pub owner_user_id: UserId,
    /// User-visible label.
    pub label: PersonalAccessTokenLabel,
    /// Token-level Git scope.
    pub scope: PersonalAccessTokenScope,
    /// Creation instant.
    pub created_at: OffsetDateTime,
    /// Exclusive expiry instant.
    pub expires_at: OffsetDateTime,
    /// Irreversible revocation instant, when present.
    pub revoked_at: Option<OffsetDateTime>,
    /// Most recent recorded successful use, when present.
    pub last_used_at: Option<OffsetDateTime>,
    /// Creation request used for audit correlation.
    pub creation_request_id: RequestId,
}

/// Safe durable PAT metadata and verifier; no bearer value is present.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PersonalAccessTokenRecord {
    id: PersonalAccessTokenId,
    verifier: PersonalAccessTokenVerifier,
    owner_user_id: UserId,
    label: PersonalAccessTokenLabel,
    scope: PersonalAccessTokenScope,
    created_at: OffsetDateTime,
    expires_at: OffsetDateTime,
    revoked_at: Option<OffsetDateTime>,
    last_used_at: Option<OffsetDateTime>,
    creation_request_id: RequestId,
}

impl PersonalAccessTokenRecord {
    /// Creates safe durable state from a newly issued plaintext token.
    ///
    /// # Errors
    ///
    /// Returns [`PersonalAccessTokenError::InvalidLifetime`] unless expiry is
    /// strictly after creation and no more than [`MAX_PAT_LIFETIME`] later.
    pub fn issue(
        token: &PersonalAccessToken,
        owner_user_id: UserId,
        label: PersonalAccessTokenLabel,
        scope: PersonalAccessTokenScope,
        created_at: OffsetDateTime,
        expires_at: OffsetDateTime,
        creation_request_id: RequestId,
    ) -> Result<Self, PersonalAccessTokenError> {
        let lifetime = expires_at - created_at;
        if lifetime <= Duration::ZERO || lifetime > MAX_PAT_LIFETIME {
            return Err(PersonalAccessTokenError::InvalidLifetime);
        }
        Ok(Self {
            id: token.id(),
            verifier: token.verifier(),
            owner_user_id,
            label,
            scope,
            created_at,
            expires_at,
            revoked_at: None,
            last_used_at: None,
            creation_request_id,
        })
    }

    /// Restores a record from trusted durable fields while rechecking all
    /// lifecycle invariants.
    ///
    /// # Errors
    ///
    /// Returns [`PersonalAccessTokenError::InvalidLifetime`] when timestamps
    /// could not have been produced by the normal issuance and lifecycle
    /// operations.
    // Durable restoration deliberately names every persisted field so schema
    // changes cannot silently bypass domain validation.
    #[allow(clippy::too_many_arguments)]
    pub fn restore(
        id: PersonalAccessTokenId,
        verifier: PersonalAccessTokenVerifier,
        owner_user_id: UserId,
        label: PersonalAccessTokenLabel,
        scope: PersonalAccessTokenScope,
        created_at: OffsetDateTime,
        expires_at: OffsetDateTime,
        revoked_at: Option<OffsetDateTime>,
        last_used_at: Option<OffsetDateTime>,
        creation_request_id: RequestId,
    ) -> Result<Self, PersonalAccessTokenError> {
        let lifetime = expires_at - created_at;
        let invalid_revocation = revoked_at.is_some_and(|at| at < created_at || at >= expires_at);
        let invalid_last_use = last_used_at.is_some_and(|at| {
            at < created_at || at >= expires_at || revoked_at.is_some_and(|revoked| at > revoked)
        });
        if lifetime <= Duration::ZERO
            || lifetime > MAX_PAT_LIFETIME
            || invalid_revocation
            || invalid_last_use
        {
            return Err(PersonalAccessTokenError::InvalidLifetime);
        }
        Ok(Self {
            id,
            verifier,
            owner_user_id,
            label,
            scope,
            created_at,
            expires_at,
            revoked_at,
            last_used_at,
            creation_request_id,
        })
    }

    /// Returns the stable non-secret identifier.
    #[must_use]
    pub const fn id(&self) -> PersonalAccessTokenId {
        self.id
    }

    /// Returns the stored one-way verifier.
    #[must_use]
    pub const fn verifier(&self) -> PersonalAccessTokenVerifier {
        self.verifier
    }

    /// Returns the user who delegated authority through this PAT.
    #[must_use]
    pub const fn owner_user_id(&self) -> UserId {
        self.owner_user_id
    }

    /// Returns safe user-visible metadata.
    #[must_use]
    pub const fn label(&self) -> &PersonalAccessTokenLabel {
        &self.label
    }

    /// Returns the normalized token-level scope.
    #[must_use]
    pub const fn scope(&self) -> &PersonalAccessTokenScope {
        &self.scope
    }

    /// Returns the creation instant.
    #[must_use]
    pub const fn created_at(&self) -> OffsetDateTime {
        self.created_at
    }

    /// Returns the exclusive expiry instant.
    #[must_use]
    pub const fn expires_at(&self) -> OffsetDateTime {
        self.expires_at
    }

    /// Returns the irreversible revocation instant, when present.
    #[must_use]
    pub const fn revoked_at(&self) -> Option<OffsetDateTime> {
        self.revoked_at
    }

    /// Returns the most recent successfully recorded use, when present.
    #[must_use]
    pub const fn last_used_at(&self) -> Option<OffsetDateTime> {
        self.last_used_at
    }

    /// Returns the creation request used for audit correlation.
    #[must_use]
    pub const fn creation_request_id(&self) -> RequestId {
        self.creation_request_id
    }

    /// Produces safe metadata for API or UI listing without the verifier.
    #[must_use]
    pub fn metadata(&self) -> PersonalAccessTokenMetadata {
        PersonalAccessTokenMetadata {
            id: self.id,
            owner_user_id: self.owner_user_id,
            label: self.label.clone(),
            scope: self.scope.clone(),
            created_at: self.created_at,
            expires_at: self.expires_at,
            revoked_at: self.revoked_at,
            last_used_at: self.last_used_at,
            creation_request_id: self.creation_request_id,
        }
    }

    /// Classifies lifecycle at the supplied trusted wall-clock instant.
    #[must_use]
    pub fn status_at(&self, at: OffsetDateTime) -> PersonalAccessTokenStatus {
        if at < self.created_at {
            PersonalAccessTokenStatus::NotYetValid
        } else if self.revoked_at.is_some_and(|revoked_at| at >= revoked_at) {
            PersonalAccessTokenStatus::Revoked
        } else if at >= self.expires_at {
            PersonalAccessTokenStatus::Expired
        } else {
            PersonalAccessTokenStatus::Active
        }
    }

    /// Checks verifier, owner, lifecycle, operation, and repository narrowing.
    ///
    /// The caller must still apply the owner's current repository
    /// authorization after this token-local check.
    ///
    /// # Errors
    ///
    /// Returns a safe denial reason without including bearer material.
    pub fn authorize_at(
        &self,
        token: &PersonalAccessToken,
        owner_user_id: UserId,
        operation: GitOperation,
        repository_id: RepositoryId,
        at: OffsetDateTime,
    ) -> Result<(), PersonalAccessTokenAuthorizationError> {
        if token.id() != self.id || !self.verifier.verifies(token) {
            return Err(PersonalAccessTokenAuthorizationError::InvalidCredential);
        }
        if owner_user_id != self.owner_user_id {
            return Err(PersonalAccessTokenAuthorizationError::WrongOwner);
        }
        match self.status_at(at) {
            PersonalAccessTokenStatus::Active => {}
            PersonalAccessTokenStatus::NotYetValid => {
                return Err(PersonalAccessTokenAuthorizationError::NotYetValid);
            }
            PersonalAccessTokenStatus::Revoked => {
                return Err(PersonalAccessTokenAuthorizationError::Revoked);
            }
            PersonalAccessTokenStatus::Expired => {
                return Err(PersonalAccessTokenAuthorizationError::Expired);
            }
        }
        if !self.scope.permits(operation, repository_id) {
            return Err(PersonalAccessTokenAuthorizationError::OutOfScope);
        }
        Ok(())
    }

    /// Records a successful use monotonically while the token is active.
    ///
    /// # Errors
    ///
    /// Returns an error when the instant is outside the active lifecycle or
    /// predates an already-recorded use.
    pub fn record_use(&mut self, at: OffsetDateTime) -> Result<(), PersonalAccessTokenError> {
        if self.status_at(at) != PersonalAccessTokenStatus::Active {
            return Err(PersonalAccessTokenError::InactiveToken);
        }
        if self.last_used_at.is_some_and(|previous| at < previous) {
            return Err(PersonalAccessTokenError::NonMonotonicLastUse);
        }
        self.last_used_at = Some(at);
        Ok(())
    }

    /// Irreversibly revokes an active token at the supplied instant.
    ///
    /// # Errors
    ///
    /// Returns an error when already revoked or when the instant is outside
    /// the token's active lifetime.
    pub fn revoke(&mut self, at: OffsetDateTime) -> Result<(), PersonalAccessTokenError> {
        if self.revoked_at.is_some() {
            return Err(PersonalAccessTokenError::AlreadyRevoked);
        }
        if self.status_at(at) != PersonalAccessTokenStatus::Active {
            return Err(PersonalAccessTokenError::InactiveToken);
        }
        self.revoked_at = Some(at);
        Ok(())
    }
}

/// PAT construction and lifecycle validation failure.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum PersonalAccessTokenError {
    /// Plaintext token envelope is not canonical version 1 syntax.
    #[error("invalid personal access token")]
    InvalidToken,
    /// Safe user-visible label is malformed.
    #[error("invalid personal access token label")]
    InvalidLabel,
    /// No Git operation was selected.
    #[error("personal access token scope must contain an operation")]
    EmptyScope,
    /// Exact repository narrowing is empty or exceeds its bound.
    #[error("invalid personal access token repository restrictions")]
    InvalidRepositoryRestrictions,
    /// Expiry is not after issuance or exceeds the hard lifetime ceiling.
    #[error("invalid personal access token lifetime")]
    InvalidLifetime,
    /// A lifecycle mutation targeted an inactive token.
    #[error("personal access token is inactive")]
    InactiveToken,
    /// Last-used metadata would move backwards.
    #[error("personal access token last-used timestamp is not monotonic")]
    NonMonotonicLastUse,
    /// Revocation was already recorded.
    #[error("personal access token is already revoked")]
    AlreadyRevoked,
}

/// Safe token-local authentication or authorization denial.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum PersonalAccessTokenAuthorizationError {
    /// Identifier or one-way verifier did not match.
    #[error("invalid personal access token credential")]
    InvalidCredential,
    /// The authenticated principal does not own this PAT.
    #[error("personal access token owner does not match")]
    WrongOwner,
    /// Trusted time predates the token's creation metadata.
    #[error("personal access token is not yet valid")]
    NotYetValid,
    /// Revocation is immediately effective.
    #[error("personal access token is revoked")]
    Revoked,
    /// Exclusive expiry has passed.
    #[error("personal access token is expired")]
    Expired,
    /// Requested Git operation or repository is outside token scope.
    #[error("personal access token does not permit this request")]
    OutOfScope,
}

fn decode_secret(encoded: &str) -> Result<[u8; PAT_SECRET_BYTES], PersonalAccessTokenError> {
    if encoded.len() != PAT_SECRET_BYTES * 2 {
        return Err(PersonalAccessTokenError::InvalidToken);
    }
    let mut secret = [0_u8; PAT_SECRET_BYTES];
    for (index, pair) in encoded.as_bytes().chunks_exact(2).enumerate() {
        let high = decode_hex_nibble(pair[0]).ok_or(PersonalAccessTokenError::InvalidToken)?;
        let low = decode_hex_nibble(pair[1]).ok_or(PersonalAccessTokenError::InvalidToken)?;
        secret[index] = (high << 4) | low;
    }
    Ok(secret)
}

const fn decode_hex_nibble(value: u8) -> Option<u8> {
    match value {
        b'0'..=b'9' => Some(value - b'0'),
        b'a'..=b'f' => Some(value - b'a' + 10),
        _ => None,
    }
}

fn encode_hex_into(bytes: &[u8], output: &mut String) {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    for byte in bytes {
        output.push(char::from(HEX[usize::from(byte >> 4)]));
        output.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
}

fn constant_time_eq(left: &[u8; 32], right: &[u8; 32]) -> bool {
    let difference = left
        .iter()
        .zip(right)
        .fold(0_u8, |difference, (left, right)| {
            difference | (left ^ right)
        });
    difference == 0
}

#[cfg(test)]
mod tests {
    use super::{
        MAX_PAT_LIFETIME, MAX_REPOSITORY_RESTRICTIONS, PersonalAccessToken,
        PersonalAccessTokenAuthorizationError, PersonalAccessTokenError, PersonalAccessTokenId,
        PersonalAccessTokenLabel, PersonalAccessTokenRecord, PersonalAccessTokenScope,
        PersonalAccessTokenStatus,
    };
    use forge_domain::RepositoryId;
    use git_capability_domain::GitOperation;
    use identity_domain::{RequestId, UserId};
    use time::{Duration, OffsetDateTime};

    const SENTINEL_SECRET: [u8; 32] = [0x5a; 32];

    fn issued_record(
        token: &PersonalAccessToken,
        owner: UserId,
        repository: RepositoryId,
        created_at: OffsetDateTime,
    ) -> PersonalAccessTokenRecord {
        PersonalAccessTokenRecord::issue(
            token,
            owner,
            PersonalAccessTokenLabel::parse("developer laptop").expect("label should validate"),
            PersonalAccessTokenScope::new(
                [GitOperation::Discover, GitOperation::Fetch],
                Some([repository]),
            )
            .expect("scope should validate"),
            created_at,
            created_at + Duration::days(30),
            RequestId::new(),
        )
        .expect("record should validate")
    }

    #[test]
    fn canonical_token_round_trips_and_rejects_noncanonical_forms() {
        let token = PersonalAccessToken::from_secret(PersonalAccessTokenId::new(), SENTINEL_SECRET);
        let exposed = token.expose();
        let parsed = PersonalAccessToken::parse(&exposed).expect("canonical token should parse");
        assert_eq!(parsed.id(), token.id());
        assert!(token.verifier().verifies(&parsed));

        for malformed in [
            "",
            "heph_pat_v2.00000000-0000-0000-0000-000000000000.00",
            "heph_pat_v1.00000000000000000000000000000000.0000000000000000000000000000000000000000000000000000000000000000",
            "heph_pat_v1.00000000-0000-0000-0000-000000000000.000000000000000000000000000000000000000000000000000000000000000G",
            "heph_pat_v1.00000000-0000-0000-0000-000000000000.0000000000000000000000000000000000000000000000000000000000000000.extra",
        ] {
            assert_eq!(
                PersonalAccessToken::parse(malformed).expect_err("input must fail"),
                PersonalAccessTokenError::InvalidToken
            );
        }
    }

    #[test]
    fn verifier_is_bound_to_identifier_and_secret() {
        let id = PersonalAccessTokenId::new();
        let token = PersonalAccessToken::from_secret(id, SENTINEL_SECRET);
        let other_id =
            PersonalAccessToken::from_secret(PersonalAccessTokenId::new(), SENTINEL_SECRET);
        let mut other_secret = SENTINEL_SECRET;
        other_secret[31] ^= 1;
        let other_secret = PersonalAccessToken::from_secret(id, other_secret);
        let verifier = token.verifier();

        assert_eq!(verifier.version(), 1);
        assert!(verifier.verifies(&token));
        assert!(!verifier.verifies(&other_id));
        assert!(!verifier.verifies(&other_secret));
    }

    #[test]
    fn plaintext_is_redacted_from_formatting_and_serialization() {
        let token = PersonalAccessToken::from_secret(PersonalAccessTokenId::new(), SENTINEL_SECRET);
        let secret_hex = "5a".repeat(32);
        let representations = [
            format!("{token:?}"),
            format!("{token}"),
            serde_json::to_string(&token).expect("redacted token should serialize"),
            format!("{:?}", token.verifier()),
            serde_json::to_string(&token.verifier()).expect("verifier should serialize"),
        ];
        for representation in representations {
            assert!(!representation.contains(&secret_hex));
            assert!(!representation.contains(&token.expose()));
        }
    }

    #[test]
    fn listing_metadata_excludes_bearer_and_verifier() {
        let created_at = OffsetDateTime::from_unix_timestamp(1_700_000_000)
            .expect("fixture timestamp should validate");
        let owner = UserId::new();
        let repository = RepositoryId::new();
        let token = PersonalAccessToken::from_secret(PersonalAccessTokenId::new(), SENTINEL_SECRET);
        let record = issued_record(&token, owner, repository, created_at);
        let serialized =
            serde_json::to_string(&record.metadata()).expect("safe metadata should serialize");

        assert!(serialized.contains(&token.id().to_string()));
        assert!(!serialized.contains("verifier"));
        assert!(!serialized.contains(&token.expose()));
        assert!(!serialized.contains(&"5a".repeat(32)));
    }

    #[test]
    fn scopes_are_explicit_normalized_and_optionally_repository_bound() {
        let allowed = RepositoryId::new();
        let denied = RepositoryId::new();
        let restricted = PersonalAccessTokenScope::new(
            [GitOperation::Fetch, GitOperation::Fetch],
            Some([allowed, allowed]),
        )
        .expect("scope should normalize");
        assert_eq!(restricted.operations().len(), 1);
        assert_eq!(
            restricted.repository_restrictions().map(BTreeSet::len),
            Some(1)
        );
        assert!(restricted.permits(GitOperation::Fetch, allowed));
        assert!(!restricted.permits(GitOperation::Fetch, denied));
        assert!(!restricted.permits(GitOperation::Receive, allowed));

        let unrestricted =
            PersonalAccessTokenScope::new([GitOperation::Discover], None::<[RepositoryId; 0]>)
                .expect("unrestricted scope should validate");
        assert!(unrestricted.permits(GitOperation::Discover, denied));
        assert_eq!(
            PersonalAccessTokenScope::new([], None::<[RepositoryId; 0]>)
                .expect_err("empty operations must fail"),
            PersonalAccessTokenError::EmptyScope
        );
        assert_eq!(
            PersonalAccessTokenScope::new([GitOperation::Fetch], Some([]))
                .expect_err("empty explicit restrictions must fail"),
            PersonalAccessTokenError::InvalidRepositoryRestrictions
        );
        let too_many = (0..=MAX_REPOSITORY_RESTRICTIONS)
            .map(|_| RepositoryId::new())
            .collect::<Vec<_>>();
        assert_eq!(
            PersonalAccessTokenScope::new([GitOperation::Fetch], Some(too_many))
                .expect_err("oversized restrictions must fail"),
            PersonalAccessTokenError::InvalidRepositoryRestrictions
        );
    }

    #[test]
    fn lifecycle_expiry_revocation_and_last_use_fail_closed() {
        let created_at = OffsetDateTime::from_unix_timestamp(1_700_000_000)
            .expect("fixture timestamp should validate");
        let owner = UserId::new();
        let repository = RepositoryId::new();
        let token = PersonalAccessToken::from_secret(PersonalAccessTokenId::new(), SENTINEL_SECRET);
        let mut record = issued_record(&token, owner, repository, created_at);

        assert_eq!(
            record.status_at(created_at - Duration::SECOND),
            PersonalAccessTokenStatus::NotYetValid
        );
        assert_eq!(
            record.status_at(created_at),
            PersonalAccessTokenStatus::Active
        );
        assert!(
            record
                .authorize_at(&token, owner, GitOperation::Fetch, repository, created_at)
                .is_ok()
        );
        assert_eq!(
            record.authorize_at(
                &token,
                UserId::new(),
                GitOperation::Fetch,
                repository,
                created_at
            ),
            Err(PersonalAccessTokenAuthorizationError::WrongOwner)
        );

        let used_at = created_at + Duration::HOUR;
        record
            .record_use(used_at)
            .expect("active use should record");
        assert_eq!(record.last_used_at(), Some(used_at));
        assert_eq!(
            record
                .record_use(created_at + Duration::MINUTE)
                .expect_err("last use cannot move backwards"),
            PersonalAccessTokenError::NonMonotonicLastUse
        );

        let revoked_at = created_at + Duration::hours(2);
        record
            .revoke(revoked_at)
            .expect("active token should revoke");
        assert_eq!(
            record.status_at(revoked_at),
            PersonalAccessTokenStatus::Revoked
        );
        assert_eq!(
            record.authorize_at(&token, owner, GitOperation::Fetch, repository, revoked_at),
            Err(PersonalAccessTokenAuthorizationError::Revoked)
        );
        assert_eq!(
            record.revoke(revoked_at).expect_err("revocation is final"),
            PersonalAccessTokenError::AlreadyRevoked
        );
    }

    #[test]
    fn lifetime_is_positive_bounded_and_exclusive() {
        let created_at = OffsetDateTime::from_unix_timestamp(1_700_000_000)
            .expect("fixture timestamp should validate");
        let owner = UserId::new();
        let repository = RepositoryId::new();
        let token = PersonalAccessToken::from_secret(PersonalAccessTokenId::new(), SENTINEL_SECRET);
        let label = PersonalAccessTokenLabel::parse("ci workstation").expect("valid label");
        let scope = PersonalAccessTokenScope::new([GitOperation::Fetch], None::<[RepositoryId; 0]>)
            .expect("valid scope");
        assert_eq!(
            PersonalAccessTokenRecord::issue(
                &token,
                owner,
                label.clone(),
                scope.clone(),
                created_at,
                created_at,
                RequestId::new()
            )
            .expect_err("zero lifetime must fail"),
            PersonalAccessTokenError::InvalidLifetime
        );
        assert_eq!(
            PersonalAccessTokenRecord::issue(
                &token,
                owner,
                label,
                scope,
                created_at,
                created_at + MAX_PAT_LIFETIME + Duration::SECOND,
                RequestId::new()
            )
            .expect_err("oversized lifetime must fail"),
            PersonalAccessTokenError::InvalidLifetime
        );

        let record = issued_record(&token, owner, repository, created_at);
        assert_eq!(
            record.status_at(record.expires_at()),
            PersonalAccessTokenStatus::Expired
        );
    }

    #[test]
    fn rejected_values_never_enter_errors() {
        let sentinel = "sentinel-token-label-never-log";
        let errors = [
            PersonalAccessToken::parse(sentinel).expect_err("invalid token"),
            PersonalAccessTokenLabel::parse(format!(" {sentinel}")).expect_err("invalid label"),
        ];
        for error in errors {
            assert!(!format!("{error:?}").contains(sentinel));
            assert!(!error.to_string().contains(sentinel));
        }
    }

    use std::collections::BTreeSet;
}
