//! Versioned host-to-guest protocol spoken with `heph-init`.

#[path = "protocol/constants.rs"]
mod constants;
#[path = "protocol/messages.rs"]
mod messages;

pub use constants::{
    GATEWAY_HANDLER_CONTRACT_LABEL, GATEWAY_HANDLER_CONTRACT_V1, GUEST_RUNTIME_AUTHORITY_PATH,
    GUEST_VSOCK_PORT, MAX_FRAME_SIZE, MAX_GATEWAY_HANDLER_OUTPUT_BYTES, MAX_LOG_CHUNK_SIZE,
    MAX_MAILBOX_PUBLICATION_BODY_BYTES, MAX_MAILBOX_PUBLICATION_CONTENT_TYPE_BYTES,
    MAX_MAILBOX_PUBLICATION_DEDUPLICATION_KEY_BYTES, MAX_MAILBOX_PUBLICATION_HEADER_NAME_BYTES,
    MAX_MAILBOX_PUBLICATION_HEADER_VALUE_BYTES, MAX_MAILBOX_PUBLICATION_HEADERS,
    MAX_MAILBOX_PUBLICATION_METHOD_BYTES, MAX_MAILBOX_PUBLICATION_ROUTE_BYTES,
    MAX_MAILBOX_PUBLICATION_SLOT_BYTES, MAX_MAILBOX_PUBLICATION_TRACE_CONTEXT_BYTES,
    MAX_METRIC_LABELS, MAX_METRIC_TEXT_SIZE, MAX_PRIVATE_HTTP_BODY_BYTES, MAX_PRIVATE_HTTP_HEADERS,
    MAX_RESULT_MESSAGE_SIZE, PRIVATE_SERVICE_CHALLENGE_BYTES, PRIVATE_SERVICE_HANDSHAKE_MAGIC,
    PRIVATE_SERVICE_HANDSHAKE_VERSION, PRIVATE_SERVICE_VSOCK_PORT, PROTOCOL_VERSION,
    RUNTIME_AUTHORITY_PATH_ENV, RUNTIME_GIT_CREDENTIAL_HELPER, RUNTIME_GIT_HOST_ENV,
    RUNTIME_GIT_LOOPBACK_PORT, RUNTIME_GIT_PATH_ENV, RUNTIME_GIT_VSOCK_PORT,
    SECRET_BROKER_VSOCK_PORT,
};
pub(crate) use constants::{
    GUEST_CONTROL_SOCKET_NAME, PRIVATE_SERVICE_SOCKET_NAME, SUPERVISOR_SOCKET_NAME,
};
pub use messages::*;
