[package]
name = "release-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[package.metadata.hephaestus]
layer = "application"
context = "release"

[dependencies]
async-trait.workspace = true
capability-domain = { path = "../../../auth/authorization/capability-domain" }
gateway-domain = { path = "../../../platform/gateway/domain" }
forge-domain = { path = "../../domain" }
git-capability-domain = { path = "../../git-capability" }
identity-domain = { path = "../../../auth/identity/domain" }
release-domain = { path = "../domain" }
runtime-types = { path = "../../../platform/runtime-types" }
serde_json.workspace = true
vm-trait.workspace = true
volume-domain = { path = "../../../runtime/volume/domain" }
time.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true
