[package]
name = "identity-oidc"
description = "OIDC token and claim verification"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
identity-application = { path = "../identity-application" }
jsonwebtoken.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
